### ISSUE TITLE
normalization problem

### ISSUE THREAD

**Issue by Shunyang2018** [qcxms/PlotMS#1]
Hi,
I found in my research that normalizing to 100 will slightly decrease the similarity score:
https://github.com/qcxms/PlotMS/blob/a2b228454c7be69f9f13943d2a4d1c93348affe9/PlotMS_v5.2.f90#L599

Because usually, the reference spectra (NIST for example) are normalized to 1000, and the Fortran function int() will abort the numbers that are less than 1 when you normalize them to 100.  This will cause a problem when comparing with ref. We are missing peaks that are less than 10 on a 1000 scale. Sometimes they are isotopic peaks or even molecular ions.

A very small detail, but I always use 1000 in my simulation.

Best,
Shunyang

**Comment by tobigithub** [comment]
Paper related to difference in accurate masses and
including references to older papers

https://link.springer.com/article/10.1007/s13361-011-0326-2


References are mentioned in the section here that for all the associated tools
contain the relevant papers.

(IsoPro [20], Mercury [15], Emass [16], NeutronCluster [18], and IsoDalton [21])

https://doi.org/10.1021%2Fac951158i

https://doi.org/10.1016%2Fj.jasms.2005.12.001

https://doi.org/10.1016%2Fj.jasms.2008.10.007

https://doi.org/10.1016%2Fj.jasms.2007.05.016

https://doi.org/10.1002%2Frcm.1290090122

**Comment by JayTheDog** [comment]
Thanks a lot for bringing this up!
Fixed to normalize to **1000 instead of 100** in update #8
