### ISSUE TITLE
add tungsten (Wolfram) [improvement]

### ISSUE THREAD

**Issue by tobigithub** [qcxms/PlotMS#2]
Hi,
tungsten compounds are sometimes used for theoretical investigations.
Experimental mass spectra exist:
https://webbook.nist.gov/cgi/cbook.cgi?ID=C14040110&Mask=200
Not sure if xtb is parametrized for element W (74)

Data is from IUPAC:
N. E. Holden et al.: IUPAC Periodic Table of the Elements and Isotopes (IPTEI)
https://iupac.org/wp-content/uploads/2015/02/IPTEI_postprint_20190301.pdf

````
ISO      ISO-MASS         MOL-FRAC
180W†    179.946713      0.0012
182W     181.948206      0.2650
183W     182.950225      0.1431
184W     183.950933      0.3064
186W     185.954365      0.2843
````
It looks interesting, lost a tooth on the right side:

![image](https://user-images.githubusercontent.com/2569565/128746682-cfe03b2d-d10c-4183-89c4-0da9a35ca37a.png)

T.

**Comment by JayTheDog** [comment]
Tungsten (Wolfram) is parametrized in GFNn-xTB, so this should work 
Added the isotope pattern in update version #8 .

**Comment by tobigithub** [comment]
@JayTheDog 
Thank you!
T
