### ISSUE TITLE
export accurate isotopic masses [improvement]

### ISSUE THREAD

**Issue by tobigithub** [qcxms/PlotMS#3]
Hi,
this is for version PlotMS 5.1 I am keeping this as a placeholder, just to collect some
literature and information. Maybe can be merged from our former developments.

It is important to export accurate masses, because most modern mass spectrometers 
record accurate masses. Also many advanced instruments are high-resolution instruments,
it is important to collect the accurate isotopic masses and export them. In terms of accuracy
it would be worthwhile to observe **six decimal places** (which is already done in 5.1).

All isotopic masses and abundances are recorded here:
N. E. Holden et al.: IUPAC Periodic Table of the Elements and Isotopes (IPTEI)
https://iupac.org/wp-content/uploads/2015/02/IPTEI_postprint_20190301.pdf
Tobias

**Comment by JayTheDog** [comment]
With the new update #8 , **PlotMS version 6.0** and higher provide exact masses for the calculated spectra.
